print("Hello, this is my weekday daily routin")
print("First I wake up")
print("I then go to the toilet and freshen up.")
print("On weekdays, I then change into my school uniform and eat breakfast.")
print("After that, I leave at 7:55 for school and reach back home at 3:15.")
print("Then I change to normal clothes and eat my lunch.")
print("From 4:30 to 6:00 I normally study unless I have sport activites or classes.")
print("From 6 o'clock, I play games for half an hour (until 6:30).")
print("Then I have free time for an hour and half (till 8:00).")
print("I then eat my dinner till 9:00, and read a book till 9:30 and then I sleep.")